version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlite_flask_web
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    user: flaskuser  # Запускаем от непривилегированного пользователя
